#spring.application.name=pwii
spring:
  application:
    name: "pwii"

  datasource:
    url: jdbc:sqlite:src/main/resources/db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""

  flyway:
    enabled: true
    locations: classpath:db/migration/structure, classpath:db/migration/data # the location where flyway should look for migration scripts
    validate-on-migrate: true

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true;

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true